# hydra config for generating cross-validation index mapping
hydra:
  run:
    dir: ${data.unity.root_path}/index_mapping/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${data.unity.root_path}/index_mapping/hydra_sweeps
    subdir: ${now:%Y-%m-%d}/${now:%H-%M-%S}

data:
  unity:
    root_path: /home/kaixu_chen/skiing/data/skiing_unity_dataset
    data_path: ${data.unity.root_path}/data_pole_ski
    sam_3d_body_results_path: ${data.unity.root_path}/sam3d_body_results/inference
    sam3_results_path: ${data.unity.root_path}/sam3_results/inference
  sam3d_export_path: ${data.unity.root_path}/sam3d_body_results/modalities_from_sam3d

cross_validation:
  # 生成 index mapping 的配置（用于 pose2equip/tools/cross_validation/main.py）
  num_persons: 2
  num_actions: 12
  num_cameras: 108
  strategies: [by_action]
  n_splits: 2
  force_recreate: false
  use_layer_camera_filter: true
  selected_layers: [0, 1, 2, 3, 4]
  selected_cameras_per_layer: # 隔90度选择一个摄像头，确保每层都有覆盖
    0: [0, 90, 180, 270]
    1: [0, 90, 180, 270]
    2: [0, 90, 180, 270]
    3: [0, 90, 180, 270]
    4: [0, 90, 180, 270]
