# hydra config
hydra:
  run:
    dir: ${log_path} # the log path, used for log and checkpoint
  sweep:
    dir: logs/
    subdir: ${experiment}/${now:%Y-%m-%d}/${now:%H-%M-%S}

loss:
  lr: 0.001
  weight_decay: 0.01

cross_validation:
  # 生成 index mapping 的配置（用于 cross_validation/generate_cv_index.py）
  num_persons: 2
  num_actions: 12
  num_cameras: 108
  strategies: [by_action]
  n_splits: 5
  force_recreate: false
  use_layer_camera_filter: true
  selected_layers: [0, 1, 2, 3, 4]
  selected_cameras_per_layer: # 隔90度选择一个摄像头，确保每层都有覆盖
    0: [0, 90, 180, 270]
    1: [0, 90, 180, 270]
    2: [0, 90, 180, 270]
    3: [0, 90, 180, 270]
    4: [0, 90, 180, 270]

data:
  raw:
    root_path: /home/kaixu_chen/skiing/data
    video_path: ${data.raw.root_path}/raw_data
    sam_3d_body_results_path: ${data.raw.root_path}/sam3d_body_results/person # 没有标签的训练数据
    sam3_results_path: ${data.raw.root_path}/sam3_results/person # 没有标签的训练数据

  unity:
    root_path: /home/kaixu_chen/skiing/data/skiing_unity_dataset
    data_path: ${data.unity.root_path}/data_pole_ski
    sam_3d_body_results_path: ${data.unity.root_path}/sam3d_body_results/inference # 有标签的训练数据
    sam3_results_path: ${data.unity.root_path}/sam3_results/inference # 只有2d标签的训练数据

  index_mapping: ${data.unity.root_path}/index_mapping # precomputed index mapping directory
  # index_mapping_file: camera_pairs_by_action.json # precomputed index mapping json file name
  index_mapping_path: ${data.index_mapping}/use_layer_camera_filter_disabled/camera_pairs_by_action_folds # precomputed index mapping json file path
  sam3d_export_path: ${data.unity.root_path}/sam3d_body_results/modalities_from_sam3d # exported kpt2d/kpt3d from SAM3D

  img_size: 224

  load_frames: true # whether to load video frames
  load_2d_kpt: false # whether to load 2d keypoints
  load_3d_kpt: true
  load_mask: false

  time_window: 16

  num_workers: 16
  batch_size: 32

model:
  backbone: stgcn # pose2equip, stgcn, 3dcnn

train:
  # Training config
  max_epochs: 50 # numer of epochs of training

  gpu: 0 # choices=[0, 1], help='the gpu number whicht to train'
  fold: 0 # the fold number for cross validation

trainer:
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  num_sanity_val_steps: 2

# Used only when model.backbone=pose2equip
pose2equip:
  num_joints: 15
  dino_model_name: facebook/dinov2-base
  dino_freeze: true
  dino_image_size: 224

  loss_w_sym: 0.03
  loss_w_len_abs: 0.2
  loss_w_temporal_smooth: 0.02
  predict_anchor_offsets: true
  loss_w_dino_feat: 0.1

  # 这里应该是过滤之后的idx
  left_ankle_idx: 10
  right_ankle_idx: 11
  left_wrist_idx: 12
  right_wrist_idx: 13
  left_foot_idx: 10
  right_foot_idx: 11
  left_hand_idx: 13
  right_hand_idx: 12

  # GT点索引，应该和unity记录的GT点顺序一致，或者至少保证能正确选取对应的点进行训练
  ski_gt_idx: [1, 2, 4, 5] # ski_l_front, ski_l_back, ski_r_front, ski_r_back
  pole_gt_idx: [0, 1, 2, 3] # pole_l_handle, pole_l_tip, pole_r_handle, pole_r_tip

experiment: ${model.backbone} # the experiment name, used for log path
log_path: logs/train_unity/${experiment}/${now:%Y-%m-%d}/fold_${train.fold}

# python -m project.main model.backbone=stgcn data.load_frames=false
